# Generated by Django 4.2.18 on 2025-06-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mullmine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agreed_terms_and_privacy',
            field=models.BooleanField(default=True),
        ),
    ]
