# Generated by Django 4.2.18 on 2025-06-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mullmine', '0002_alter_user_agreed_terms_and_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agreed_terms_and_privacy',
        ),
    ]
