# Generated by Django 4.2.18 on 2025-02-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='display_name',
        ),
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.CharField(default='What is your question?', max_length=255),
            preserve_default=False,
        ),
    ]
