# Generated by Django 4.2.18 on 2025-04-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0002_remove_room_display_name_room_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ChatTopic',
        ),
    ]
