# Generated by Django 4.2.16 on 2024-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0003_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_num_members',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
