# Generated by Django 4.2.18 on 2025-05-06 18:32

from django.db import migrations


def create_philly(apps, schema_editor):
    User = apps.get_model("blabhere", "User")
    User.objects.get_or_create(
        display_name="Philly the Philosophy Bot", is_verified=True
    )


def delete_philly(apps, schema_editor):
    User = apps.get_model("blabhere", "User")
    User.objects.filter(display_name="Philly the Philosophy Bot").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blabhere", "0003_remove_room_topic_delete_chattopic"),
    ]

    operations = [
        migrations.RunPython(create_philly, delete_philly),
    ]
