# Generated by Django 4.2.16 on 2024-10-17 12:58

from django.db import migrations


def make_display_names_unique(apps, schema_editor):
    Room = apps.get_model("blabhere", "Room")
    User = apps.get_model("blabhere", "User")
    for room in Room.objects.all():
        room.display_name = str(room.id)
        room.save(update_fields=["display_name"])
    for user in User.objects.all():
        user.display_name = str(user.id)
        user.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("blabhere", "0005_conversation"),
    ]

    operations = [
        migrations.RunPython(
            make_display_names_unique, reverse_code=migrations.RunPython.noop
        ),
    ]
