# Generated by Django 4.2.16 on 2024-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0008_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
