# Generated by Django 4.2.16 on 2024-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0009_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='room',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_num_members',
        ),
    ]
