# Generated by Django 4.2.16 on 2024-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0010_remove_room_creator_remove_room_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chat_topics',
            field=models.ManyToManyField(related_name='users', to='blabhere.chattopic'),
        ),
    ]
