# Generated by Django 4.2.16 on 2024-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0011_chattopic_user_chat_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_terms_and_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
