# Generated by Django 4.2.16 on 2024-11-22 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0012_user_agreed_terms_and_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
