# Generated by Django 4.2.16 on 2024-11-25 21:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0014_alter_user_blocked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_chats', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
