# Generated by Django 4.2.16 on 2024-11-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0016_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='display_name',
            field=models.CharField(default='helloworld', max_length=150),
            preserve_default=False,
        ),
    ]
