# Generated by Django 4.2.16 on 2024-12-03 15:46

from django.db import migrations, models
import django.db.models.deletion


def gen_default(apps):
    Room = apps.get_model("blabhere", "Room")
    return Room.objects.all().first().pk


class Migration(migrations.Migration):
    from django.apps import apps

    dependencies = [
        ("blabhere", "0017_room_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportedchat",
            name="messages",
        ),
        migrations.AddField(
            model_name="reportedchat",
            name="reported_room",
            field=models.ForeignKey(
                default=gen_default(apps),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="blabhere.room",
            ),
            preserve_default=False,
        ),
    ]
