# Generated by Django 4.2.16 on 2025-01-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blabhere', '0018_remove_reportedchat_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_topics',
        ),
    ]
